name: main
on:
  push:
    branches: [ main ]

concurrency: 
  group: main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: mkdir _TMP_
      - run: cd _TMP_
      - run: curl https://master.dl.sourceforge.net/project/crunchme/v0.4/crunchme-0.4.zip?viasf=1 -o min.zip
          
      - uses: montudor/action-zip@v1
        with:
          args: unzip min.zip
          
      - run: cd crunchme-0.4
      - run: dir
