name: main
on:
  push:
    branches: [ main ]

concurrency: 
  group: main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo chown -R $USER:$USER ${{ github.workspace }}
    
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}

      - run: mkdir _TMP_; cd _TMP_; curl https://master.dl.sourceforge.net/project/crunchme/v0.4/crunchme-0.4.zip?viasf=1 -o min.zip
          
      - uses: montudor/action-zip@v1
        with:
          args: unzip _TMP_/min.zip -d _TMP_
          
      - run: ./_TMP_/crunchme-0.4/bin/crunchme-linux-amd64 -nostrip ./src/main.js jsRUNpy.min.extreme.js
      # - run: echo "$(cat jsRUNpy.js)"
      - run: sudo rm -r _TMP_; cp ./src/main.js jsRUNpy.js
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'crunchme : Commit Pipeline'
          branch: ${{ github.ref }}
