name: main
on:
  push:
    branches: [ main ]

concurrency: 
  group: main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo chown -R $USER:$USER /home/github/actions-runner/_work/jsRUNpy.js
    
      - uses: actions/checkout@v2

      - run: mkdir _TMP_; cd _TMP_; curl https://master.dl.sourceforge.net/project/crunchme/v0.4/crunchme-0.4.zip?viasf=1 -o min.zip
          
      - uses: montudor/action-zip@v1
        with:
          args: unzip _TMP_/min.zip -d _TMP_
          
      - run: ./_TMP_/crunchme-0.4/bin/crunchme-linux-amd64 -nostrip ./src/main.js jsRUNpy.js
      # - run: echo "$(cat jsRUNpy.js)"
      - run: rm -r _TMP_
